# Generated by carnix 0.4.14: carnix ./../ircbot/Cargo.lock --output ./ircbot-carnix.nix
{ buildPlatform, buildRustCrate, fetchgit }:
let kernel = buildPlatform.parsed.kernel.name;
    abi = buildPlatform.parsed.abi.name;
    advapi32_sys_0_2_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "advapi32-sys";
      version = "0.2.0";
      authors = [ "Peter Atashian <retep998@gmail.com>" ];
      sha256 = "1l6789hkz2whd9gklwz1m379kcvyizaj8nnzj3rn4a5h79yg59v7";
      libName = "advapi32";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    aho_corasick_0_5_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "aho-corasick";
      version = "0.5.3";
      authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
      sha256 = "1igab46mvgknga3sxkqc917yfff0wsjxjzabdigmh240p5qxqlnn";
      libName = "aho_corasick";
      crateBin = [ {  name = "aho-corasick-dot"; } ];
      inherit dependencies buildDependencies features;
    };
    aho_corasick_0_6_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "aho-corasick";
      version = "0.6.4";
      authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
      sha256 = "189v919mp6rzzgjp1khpn4zlq8ls81gh43x1lmc8kbkagdlpq888";
      libName = "aho_corasick";
      crateBin = [ {  name = "aho-corasick-dot"; } ];
      inherit dependencies buildDependencies features;
    };
    amq_proto_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "amq-proto";
      version = "0.1.0";
      authors = [ "Andrii Dmytrenko <refresh.xss@gmail.com>" ];
      sha256 = "0333fsph61q9nxbx6h8hdxjmpabjm9vmsfc6q5agy801x35r4ml9";
      inherit dependencies buildDependencies features;
    };
    amqp_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "amqp";
      version = "0.1.0";
      authors = [ "Andrii Dmytrenko <andrey@reevoo.com>" ];
      src = fetchgit {
         url = "https://github.com/grahamc/rust-amqp.git";
         rev = "8f40d623cf94af15a2e1e120cdf1d8c6f157e881";
         sha256 = "1wqxw81cwarhfxp5mgfa8ygswj4rzi0xj4q6wsg93p6hcj2h3aib";
      };
      inherit dependencies buildDependencies features;
    };
    backtrace_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "backtrace";
      version = "0.3.4";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" "The Rust Project Developers" ];
      sha256 = "1caba8w3rqd5ghr88ghyz5wgkf81dgx18bj1llkax6qmianc6gk7";
      inherit dependencies buildDependencies features;
    };
    backtrace_sys_0_1_16_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "backtrace-sys";
      version = "0.1.16";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "1cn2c8q3dn06crmnk0p62czkngam4l8nf57wy33nz1y5g25pszwy";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    bit_vec_0_4_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "bit-vec";
      version = "0.4.4";
      authors = [ "Alexis Beingessner <a.beingessner@gmail.com>" ];
      sha256 = "06czykmn001z6c3a4nsrpc3lrj63ga0kzp7kgva9r9wylhkkqpq9";
      inherit dependencies buildDependencies features;
    };
    bitflags_0_7_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "bitflags";
      version = "0.7.0";
      authors = [ "The Rust Project Developers" ];
      sha256 = "1hr72xg5slm0z4pxs2hiy4wcyx3jva70h58b7mid8l0a4c8f7gn5";
      inherit dependencies buildDependencies features;
    };
    bitflags_0_9_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "bitflags";
      version = "0.9.1";
      authors = [ "The Rust Project Developers" ];
      sha256 = "18h073l5jd88rx4qdr95fjddr9rk79pb1aqnshzdnw16cfmb9rws";
      inherit dependencies buildDependencies features;
    };
    bufstream_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "bufstream";
      version = "0.1.3";
      authors = [ "The Rust Project Developers" ];
      sha256 = "011ihrdvj4mm3yd2jgq1z554clnimvfv6wnbgdwjccfvn1qn3d4s";
      inherit dependencies buildDependencies features;
    };
    byteorder_0_5_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "byteorder";
      version = "0.5.3";
      authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
      sha256 = "0zsr6b0m0yl5c0yy92nq7srfpczd1dx1xqcx3rlm5fbl8si9clqx";
      inherit dependencies buildDependencies features;
    };
    byteorder_1_2_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "byteorder";
      version = "1.2.1";
      authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
      sha256 = "1wsxnqcscg4gchdmgdbwc78lw2qx2i6bnjd564xq7h7qc4fp2157";
      inherit dependencies buildDependencies features;
    };
    bytes_0_4_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "bytes";
      version = "0.4.5";
      authors = [ "Carl Lerche <me@carllerche.com>" ];
      sha256 = "09grypiv7wnqbhsmini1i77d5bwcna6nzp3yhh9i02hn37ma58vn";
      inherit dependencies buildDependencies features;
    };
    cc_1_0_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "cc";
      version = "1.0.3";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "193pwqgh79w6k0k29svyds5nnlrwx44myqyrw605d5jj4yk2zmpr";
      inherit dependencies buildDependencies features;
    };
    cfg_if_0_1_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "cfg-if";
      version = "0.1.2";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "0x06hvrrqy96m97593823vvxcgvjaxckghwyy2jcyc8qc7c6cyhi";
      inherit dependencies buildDependencies features;
    };
    chrono_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "chrono";
      version = "0.4.0";
      authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
      sha256 = "0hm53hi6v7b6b1va6vn96lx26wvj8gzi2g51s1j02nlz0jcprw6a";
      inherit dependencies buildDependencies features;
    };
    core_foundation_0_2_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "core-foundation";
      version = "0.2.3";
      authors = [ "The Servo Project Developers" ];
      sha256 = "1g0vpya5h2wa0nlz4a74jar6y8z09f0p76zbzfqrm3dbfsrld1pm";
      inherit dependencies buildDependencies features;
    };
    core_foundation_sys_0_2_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "core-foundation-sys";
      version = "0.2.3";
      authors = [ "The Servo Project Developers" ];
      sha256 = "19s0d03294m9s5j8cvy345db3gkhs2y02j5268ap0c6ky5apl53s";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    crypt32_sys_0_2_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "crypt32-sys";
      version = "0.2.0";
      authors = [ "Peter Atashian <retep998@gmail.com>" ];
      sha256 = "1vy1q3ayc7f4wiwyxw31hd12cvs7791x3by6ka9wbxhm5gzfs3d0";
      libName = "crypt32";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    dbghelp_sys_0_2_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "dbghelp-sys";
      version = "0.2.0";
      authors = [ "Peter Atashian <retep998@gmail.com>" ];
      sha256 = "0ylpi3bbiy233m57hnisn1df1v0lbl7nsxn34b0anzsgg440hqpq";
      libName = "dbghelp";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    dtoa_0_4_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "dtoa";
      version = "0.4.2";
      authors = [ "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "1bxsh6fags7nr36vlz07ik2a1rzyipc8x1y30kjk832hf2pzadmw";
      inherit dependencies buildDependencies features;
    };
    encoding_0_2_33_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "encoding";
      version = "0.2.33";
      authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
      sha256 = "16ls6avhv5ll28zajl5q1jbiz1g80c4ygnw13zzqmij14wsp5329";
      inherit dependencies buildDependencies features;
    };
    encoding_index_japanese_1_20141219_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "encoding-index-japanese";
      version = "1.20141219.5";
      authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
      sha256 = "1pmfaabps0x6v6cd4fbk9ssykhkmc799dma2y78fhk7gvyr5gyl4";
      libPath = "lib.rs";
      libName = "encoding_index_japanese";
      inherit dependencies buildDependencies features;
    };
    encoding_index_korean_1_20141219_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "encoding-index-korean";
      version = "1.20141219.5";
      authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
      sha256 = "1b756n7gcilkx07y7zjrikcg0b8v8yd6mw8w01ji8sp3k1cabcf2";
      libPath = "lib.rs";
      libName = "encoding_index_korean";
      inherit dependencies buildDependencies features;
    };
    encoding_index_simpchinese_1_20141219_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "encoding-index-simpchinese";
      version = "1.20141219.5";
      authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
      sha256 = "0rb4xd8cqymhqffqqxdk18mf9n354vs50ar66jrysb1z6ymcvvpy";
      libPath = "lib.rs";
      libName = "encoding_index_simpchinese";
      inherit dependencies buildDependencies features;
    };
    encoding_index_singlebyte_1_20141219_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "encoding-index-singlebyte";
      version = "1.20141219.5";
      authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
      sha256 = "07df3jrfwfmzi2s352lvcpvy5dqpy2s45d2xx2dz1x7zh3q5284d";
      libPath = "lib.rs";
      libName = "encoding_index_singlebyte";
      inherit dependencies buildDependencies features;
    };
    encoding_index_tradchinese_1_20141219_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "encoding-index-tradchinese";
      version = "1.20141219.5";
      authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
      sha256 = "0lb12nbv29cy41gx26yz3v4kfi8h1xbn1ppja8szgqi2zm1wlywn";
      libPath = "lib.rs";
      libName = "encoding_index_tradchinese";
      inherit dependencies buildDependencies features;
    };
    encoding_index_tests_0_1_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "encoding_index_tests";
      version = "0.1.4";
      authors = [ "Kang Seonghoon <public+rust@mearie.org>" ];
      sha256 = "0z09kwh4z76q00cfr081rgjbnai4s2maq2vk88lgrq9d6bkf93f6";
      libPath = "index_tests.rs";
      inherit dependencies buildDependencies features;
    };
    enum_primitive_0_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "enum_primitive";
      version = "0.1.1";
      authors = [ "Anders Kaseorg <andersk@mit.edu>" ];
      sha256 = "1a225rlsz7sz3nn14dar71kp2f9v08s3rwl6j55xp51mv01f695y";
      inherit dependencies buildDependencies features;
    };
    env_logger_0_3_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "env_logger";
      version = "0.3.5";
      authors = [ "The Rust Project Developers" ];
      sha256 = "1mvxiaaqsyjliv1mm1qaagjqiccw11mdyi3n9h9rf8y6wj15zycw";
      inherit dependencies buildDependencies features;
    };
    env_logger_0_4_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "env_logger";
      version = "0.4.3";
      authors = [ "The Rust Project Developers" ];
      sha256 = "0nrx04p4xa86d5kc7aq4fwvipbqji9cmgy449h47nc9f1chafhgg";
      inherit dependencies buildDependencies features;
    };
    error_chain_0_10_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "error-chain";
      version = "0.10.0";
      authors = [ "Brian Anderson <banderson@mozilla.com>" "Paul Colomiets <paul@colomiets.name>" "Colin Kiegel <kiegel@gmx.de>" "Yamakaky <yamakaky@yamaworld.fr>" ];
      sha256 = "1xxbzd8cjlpzsb9fsih7mdnndhzrvykj0w77yg90qc85az1xwy5z";
      inherit dependencies buildDependencies features;
    };
    foreign_types_0_3_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "foreign-types";
      version = "0.3.2";
      authors = [ "Steven Fackler <sfackler@gmail.com>" ];
      sha256 = "105n8sp2djb1s5lzrw04p7ss3dchr5qa3canmynx396nh3vwm2p8";
      inherit dependencies buildDependencies features;
    };
    foreign_types_shared_0_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "foreign-types-shared";
      version = "0.1.1";
      authors = [ "Steven Fackler <sfackler@gmail.com>" ];
      sha256 = "0b6cnvqbflws8dxywk4589vgbz80049lz4x1g9dfy4s1ppd3g4z5";
      inherit dependencies buildDependencies features;
    };
    fuchsia_zircon_0_2_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "fuchsia-zircon";
      version = "0.2.1";
      authors = [ "Raph Levien <raph@google.com>" ];
      sha256 = "0yd4rd7ql1vdr349p6vgq2dnwmpylky1kjp8g1zgvp250jxrhddb";
      inherit dependencies buildDependencies features;
    };
    fuchsia_zircon_sys_0_2_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "fuchsia-zircon-sys";
      version = "0.2.0";
      authors = [ "Raph Levien <raph@google.com>" ];
      sha256 = "1yrqsrjwlhl3di6prxf5xmyd82gyjaysldbka5wwk83z11mpqh4w";
      inherit dependencies buildDependencies features;
    };
    futures_0_1_17_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "futures";
      version = "0.1.17";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "1awrl30p1yqc0l9hbhng0f2873h2wr2244caj20b706plwqmcw0y";
      inherit dependencies buildDependencies features;
    };
    idna_0_1_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "idna";
      version = "0.1.4";
      authors = [ "The rust-url developers" ];
      sha256 = "15j44qgjx1skwg9i7f4cm36ni4n99b1ayx23yxx7axxcw8vjf336";
      inherit dependencies buildDependencies features;
    };
    iovec_0_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "iovec";
      version = "0.1.1";
      authors = [ "Carl Lerche <me@carllerche.com>" ];
      sha256 = "14fns3g3arbql6lkczf2gbbzaqh22mfv7y1wq5rr2y8jhh5m8jmm";
      inherit dependencies buildDependencies features;
    };
    irc_0_12_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "irc";
      version = "0.12.5";
      authors = [ "Aaron Weiss <awe@pdgn.co>" ];
      sha256 = "05xn4p7d8r7575kb0n07hbrvjgdd5d2myz027nadkpipdriiv7v2";
      inherit dependencies buildDependencies features;
    };
    ircbot_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "ircbot";
      version = "0.1.0";
      authors = [ "Graham Christensen <graham@grahamc.com>" ];
      src = ./../ircbot;
      inherit dependencies buildDependencies features;
    };
    itoa_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "itoa";
      version = "0.3.4";
      authors = [ "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "1nfkzz6vrgj0d9l3yzjkkkqzdgs68y294fjdbl7jq118qi8xc9d9";
      inherit dependencies buildDependencies features;
    };
    kernel32_sys_0_2_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "kernel32-sys";
      version = "0.2.2";
      authors = [ "Peter Atashian <retep998@gmail.com>" ];
      sha256 = "1lrw1hbinyvr6cp28g60z97w32w8vsk6pahk64pmrv2fmby8srfj";
      libName = "kernel32";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    lazy_static_0_2_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "lazy_static";
      version = "0.2.11";
      authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
      sha256 = "1x6871cvpy5b96yv4c7jvpq316fp5d4609s9py7qk6cd6x9k34vm";
      inherit dependencies buildDependencies features;
    };
    lazy_static_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "lazy_static";
      version = "1.0.0";
      authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
      sha256 = "0wfvqyr2nvx2mbsrscg5y7gfa9skhb8p72ayanl8vl49pw24v4fh";
      inherit dependencies buildDependencies features;
    };
    lazycell_0_5_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "lazycell";
      version = "0.5.1";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" "Nikita Pekin <contact@nikitapek.in>" ];
      sha256 = "1ds71sc24vnhfy0ys1v46qn7fkcavi4brsk4jg3dp8d0yli3sd31";
      inherit dependencies buildDependencies features;
    };
    libc_0_2_34_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "libc";
      version = "0.2.34";
      authors = [ "The Rust Project Developers" ];
      sha256 = "11jmqdxmv0ka10ay0l8nzx0nl7s2lc3dbrnh1mgbr2grzwdyxi2s";
      inherit dependencies buildDependencies features;
    };
    log_0_3_8_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "log";
      version = "0.3.8";
      authors = [ "The Rust Project Developers" ];
      sha256 = "1c43z4z85sxrsgir4s1hi84558ab5ic7jrn5qgmsiqcv90vvn006";
      inherit dependencies buildDependencies features;
    };
    matches_0_1_6_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "matches";
      version = "0.1.6";
      authors = [ "Simon Sapin <simon.sapin@exyr.org>" ];
      sha256 = "1zlrqlbvzxdil8z8ial2ihvxjwvlvg3g8dr0lcdpsjclkclasjan";
      libPath = "lib.rs";
      inherit dependencies buildDependencies features;
    };
    memchr_0_1_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "memchr";
      version = "0.1.11";
      authors = [ "Andrew Gallant <jamslam@gmail.com>" "bluss" ];
      sha256 = "0x73jghamvxxq5fsw9wb0shk5m6qp3q6fsf0nibn0i6bbqkw91s8";
      inherit dependencies buildDependencies features;
    };
    memchr_2_0_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "memchr";
      version = "2.0.1";
      authors = [ "Andrew Gallant <jamslam@gmail.com>" "bluss" ];
      sha256 = "0ls2y47rjwapjdax6bp974gdp06ggm1v8d1h69wyydmh1nhgm5gr";
      inherit dependencies buildDependencies features;
    };
    mio_0_6_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "mio";
      version = "0.6.11";
      authors = [ "Carl Lerche <me@carllerche.com>" ];
      sha256 = "0maafa27rard6r62rc7iv5mcn2g0vvv6kw5as1kbf7mr4q1ph6sm";
      inherit dependencies buildDependencies features;
    };
    miow_0_2_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "miow";
      version = "0.2.1";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "14f8zkc6ix7mkyis1vsqnim8m29b6l55abkba3p2yz7j1ibcvrl0";
      inherit dependencies buildDependencies features;
    };
    native_tls_0_1_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "native-tls";
      version = "0.1.4";
      authors = [ "Steven Fackler <sfackler@gmail.com>" ];
      sha256 = "0q5y5i96mfpjbhx8y7w9rdq65mksw67m60bw4xqlybc8y6jkr99v";
      inherit dependencies buildDependencies features;
    };
    net2_0_2_31_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "net2";
      version = "0.2.31";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "13mphllfcbybsdqyi1jb3kyqx65m8ch07drr59a4wb3yl89awm7y";
      inherit dependencies buildDependencies features;
    };
    num_0_1_41_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "num";
      version = "0.1.41";
      authors = [ "The Rust Project Developers" ];
      sha256 = "05v5llf5yl4y1i89jcgqr6gwxhylrgrpv0n440c3lya7hwng9s73";
      inherit dependencies buildDependencies features;
    };
    num_integer_0_1_35_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "num-integer";
      version = "0.1.35";
      authors = [ "The Rust Project Developers" ];
      sha256 = "0xybj8isi9b6wc646d5rc043i8l8j6wy0vrl4pn995qms9fxbbcc";
      inherit dependencies buildDependencies features;
    };
    num_iter_0_1_34_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "num-iter";
      version = "0.1.34";
      authors = [ "The Rust Project Developers" ];
      sha256 = "02cld7x9dzbqbs6sxxzq1i22z3awlcd6ljkgvhkfr9rsnaxphzl9";
      inherit dependencies buildDependencies features;
    };
    num_traits_0_1_41_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "num-traits";
      version = "0.1.41";
      authors = [ "The Rust Project Developers" ];
      sha256 = "134gv890n1gv8v0jys55k0940gqp2hibgf1fs8q9jmyk2xp1jp9m";
      inherit dependencies buildDependencies features;
    };
    openssl_0_9_22_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "openssl";
      version = "0.9.22";
      authors = [ "Steven Fackler <sfackler@gmail.com>" ];
      sha256 = "1knzs1fqh0izijc9d0jz35x9vv5bfjg1rkngpvbkfyjsmsasym71";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    openssl_sys_0_9_22_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "openssl-sys";
      version = "0.9.22";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" "Steven Fackler <sfackler@gmail.com>" ];
      sha256 = "1l2zp6nb9073kxmpq076c5x82w6mwkb4cpsrm5y2j6dnf7aywrn3";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    percent_encoding_1_0_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "percent-encoding";
      version = "1.0.1";
      authors = [ "The rust-url developers" ];
      sha256 = "04ahrp7aw4ip7fmadb0bknybmkfav0kk0gw4ps3ydq5w6hr0ib5i";
      libPath = "lib.rs";
      inherit dependencies buildDependencies features;
    };
    pkg_config_0_3_9_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "pkg-config";
      version = "0.3.9";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "06k8fxgrsrxj8mjpjcq1n7mn2p1shpxif4zg9y5h09c7vy20s146";
      inherit dependencies buildDependencies features;
    };
    quote_0_3_15_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "quote";
      version = "0.3.15";
      authors = [ "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "09il61jv4kd1360spaj46qwyl21fv1qz18fsv2jra8wdnlgl5jsg";
      inherit dependencies buildDependencies features;
    };
    rand_0_3_18_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "rand";
      version = "0.3.18";
      authors = [ "The Rust Project Developers" ];
      sha256 = "15d7c3myn968dzjs0a2pgv58hzdavxnq6swgj032lw2v966ir4xv";
      inherit dependencies buildDependencies features;
    };
    redox_syscall_0_1_32_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "redox_syscall";
      version = "0.1.32";
      authors = [ "Jeremy Soller <jackpot51@gmail.com>" ];
      sha256 = "1axxj8x6ngh6npkzqc5h216fajkcyrdxdgb7m2f0n5xfclbk47fv";
      libName = "syscall";
      inherit dependencies buildDependencies features;
    };
    regex_0_1_80_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "regex";
      version = "0.1.80";
      authors = [ "The Rust Project Developers" ];
      sha256 = "0y4s8ghhx6sgzb35irwivm3w0l2hhqhmdcd2px9hirqnkagal9l6";
      inherit dependencies buildDependencies features;
    };
    regex_0_2_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "regex";
      version = "0.2.3";
      authors = [ "The Rust Project Developers" ];
      sha256 = "11a4ysci7qn336990wr20hsr2420f22hh28zcf0a90hfi3kx430z";
      inherit dependencies buildDependencies features;
    };
    regex_syntax_0_3_9_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "regex-syntax";
      version = "0.3.9";
      authors = [ "The Rust Project Developers" ];
      sha256 = "1mzhphkbwppwd1zam2jkgjk550cqgf6506i87bw2yzrvcsraiw7m";
      inherit dependencies buildDependencies features;
    };
    regex_syntax_0_4_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "regex-syntax";
      version = "0.4.1";
      authors = [ "The Rust Project Developers" ];
      sha256 = "01yrsm68lj86ad1whgg1z95c2pfsvv58fz8qjcgw7mlszc0c08ls";
      inherit dependencies buildDependencies features;
    };
    rustc_demangle_0_1_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "rustc-demangle";
      version = "0.1.5";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "096kkcx9j747700fhxj1s4rlwkj21pqjmvj64psdj6bakb2q13nc";
      inherit dependencies buildDependencies features;
    };
    schannel_0_1_9_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "schannel";
      version = "0.1.9";
      authors = [ "Steven Fackler <sfackler@gmail.com>" "Steffen Butzer <steffen.butzer@outlook.com>" ];
      sha256 = "0gcbcq9sj1c1qkncwadp3azfnzkn0115dycjmbw00zcj4jdl35a0";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    scoped_tls_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "scoped-tls";
      version = "0.1.0";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "1j8azxa15srljafrg7wc221npvxb3700sbfk6jjav0rw2zclsnf5";
      inherit dependencies buildDependencies features;
    };
    secur32_sys_0_2_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "secur32-sys";
      version = "0.2.0";
      authors = [ "Peter Atashian <retep998@gmail.com>" ];
      sha256 = "0sp46ix9mx1156bidpfiq30xxsgmpva5jffls3259kxjqlxifcnx";
      libName = "secur32";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    security_framework_0_1_16_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "security-framework";
      version = "0.1.16";
      authors = [ "Steven Fackler <sfackler@gmail.com>" ];
      sha256 = "1kxczsaj8gz4922jl5af2gkxh71rasb6khaf3dp7ldlnw9qf2sbm";
      inherit dependencies buildDependencies features;
    };
    security_framework_sys_0_1_16_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "security-framework-sys";
      version = "0.1.16";
      authors = [ "Steven Fackler <sfackler@gmail.com>" ];
      sha256 = "0ai2pivdr5fyc7czbkpcrwap0imyy0r8ndarrl3n5kiv0jha1js3";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };
    serde_1_0_23_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "serde";
      version = "1.0.23";
      authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "1jk2jggxns1hafws8nbykpfplz1rv9hgql2dm3s1v27dq1gdpar6";
      inherit dependencies buildDependencies features;
    };
    serde_derive_1_0_23_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "serde_derive";
      version = "1.0.23";
      authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "0bdrwxpl00crl6y2m9yhgp1iqhw0h19fp5ygf84viy5krjcq1kj7";
      procMacro = true;
      inherit dependencies buildDependencies features;
    };
    serde_derive_internals_0_17_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "serde_derive_internals";
      version = "0.17.0";
      authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "1g1j3v6pj9wbcz3v3w4smjpwrcdwjicmf6yd5cbai04as9iwhw74";
      inherit dependencies buildDependencies features;
    };
    serde_json_1_0_7_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "serde_json";
      version = "1.0.7";
      authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "0gbga4sbhysa0pawrpmvz5yr7sgwcc6rp5izhb81h82hd1nfw3mq";
      inherit dependencies buildDependencies features;
    };
    slab_0_3_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "slab";
      version = "0.3.0";
      authors = [ "Carl Lerche <me@carllerche.com>" ];
      sha256 = "0y6lhjggksh57hyfd3l6p9wgv5nhvw9c6djrysq7jnalz8fih21k";
      inherit dependencies buildDependencies features;
    };
    slab_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "slab";
      version = "0.4.0";
      authors = [ "Carl Lerche <me@carllerche.com>" ];
      sha256 = "1qy2vkgwqgj5z4ygdkh040n9yh1vz80v5flxb1xrvw3i4wxs7yx0";
      inherit dependencies buildDependencies features;
    };
    syn_0_11_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "syn";
      version = "0.11.11";
      authors = [ "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "0yw8ng7x1dn5a6ykg0ib49y7r9nhzgpiq2989rqdp7rdz3n85502";
      inherit dependencies buildDependencies features;
    };
    synom_0_11_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "synom";
      version = "0.11.3";
      authors = [ "David Tolnay <dtolnay@gmail.com>" ];
      sha256 = "1l6d1s9qjfp6ng2s2z8219igvlv7gyk8gby97sdykqc1r93d8rhc";
      inherit dependencies buildDependencies features;
    };
    tempdir_0_3_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "tempdir";
      version = "0.3.5";
      authors = [ "The Rust Project Developers" ];
      sha256 = "0rirc5prqppzgd15fm8ayan349lgk2k5iqdkrbwrwrv5pm4znsnz";
      inherit dependencies buildDependencies features;
    };
    thread_id_2_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "thread-id";
      version = "2.0.0";
      authors = [ "Ruud van Asseldonk <dev@veniogames.com>" ];
      sha256 = "06i3c8ckn97i5rp16civ2vpqbknlkx66dkrl070iw60nawi0kjc3";
      inherit dependencies buildDependencies features;
    };
    thread_local_0_2_7_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "thread_local";
      version = "0.2.7";
      authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
      sha256 = "19p0zrs24rdwjvpi10jig5ms3sxj00pv8shkr9cpddri8cdghqp7";
      inherit dependencies buildDependencies features;
    };
    thread_local_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "thread_local";
      version = "0.3.4";
      authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
      sha256 = "1y6cwyhhx2nkz4b3dziwhqdvgq830z8wjp32b40pjd8r0hxqv2jr";
      inherit dependencies buildDependencies features;
    };
    time_0_1_38_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "time";
      version = "0.1.38";
      authors = [ "The Rust Project Developers" ];
      sha256 = "1ws283vvz7c6jfiwn53rmc6kybapr4pjaahfxxrz232b0qzw7gcp";
      inherit dependencies buildDependencies features;
    };
    tokio_core_0_1_10_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "tokio-core";
      version = "0.1.10";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "005mpg94zgygpk2iib9sg9xi4wxsk8r9gpwbsdvfz4fzs3p6l596";
      inherit dependencies buildDependencies features;
    };
    tokio_io_0_1_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "tokio-io";
      version = "0.1.4";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" "Carl Lerche <me@carllerche.com>" ];
      sha256 = "0cq5m0mvkn6kxqw7qnwliq3yimxdbcqfdlwn7xkrik8w8xlb3m6p";
      inherit dependencies buildDependencies features;
    };
    tokio_mockstream_1_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "tokio-mockstream";
      version = "1.1.0";
      authors = [ "Aaron Weiss <awe@pdgn.co>" ];
      sha256 = "1h7g3rgpp1aih8yjz3q35cvzxsnx84lb9k32wnazwb6x03pv38fv";
      inherit dependencies buildDependencies features;
    };
    tokio_timer_0_1_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "tokio-timer";
      version = "0.1.2";
      authors = [ "Carl Lerche <me@carllerche.com>" ];
      sha256 = "0ngmxv7dzzkbs9bs39wzx11527hanpjdlyvi6gdxzi9q41q0kz7y";
      inherit dependencies buildDependencies features;
    };
    tokio_tls_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "tokio-tls";
      version = "0.1.3";
      authors = [ "Carl Lerche <me@carllerche.com>" "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "0ib58y81qr64m3gg0pn7k06b71r8b05cmvakzpgfqdsw0qj08sva";
      inherit dependencies buildDependencies features;
    };
    toml_0_4_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "toml";
      version = "0.4.5";
      authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
      sha256 = "06zxqhn3y58yzjfaykhcrvlf7p2dnn54kn3g4apmja3cn5b18lkk";
      inherit dependencies buildDependencies features;
    };
    unicode_bidi_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "unicode-bidi";
      version = "0.3.4";
      authors = [ "The Servo Project Developers" ];
      sha256 = "0lcd6jasrf8p9p0q20qyf10c6xhvw40m2c4rr105hbk6zy26nj1q";
      libName = "unicode_bidi";
      inherit dependencies buildDependencies features;
    };
    unicode_normalization_0_1_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "unicode-normalization";
      version = "0.1.5";
      authors = [ "kwantam <kwantam@gmail.com>" ];
      sha256 = "0hg29g86fca7b65mwk4sm5s838js6bqrl0gabadbazvbsgjam0j5";
      inherit dependencies buildDependencies features;
    };
    unicode_xid_0_0_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "unicode-xid";
      version = "0.0.4";
      authors = [ "erick.tryzelaar <erick.tryzelaar@gmail.com>" "kwantam <kwantam@gmail.com>" ];
      sha256 = "1dc8wkkcd3s6534s5aw4lbjn8m67flkkbnajp5bl8408wdg8rh9v";
      inherit dependencies buildDependencies features;
    };
    unreachable_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "unreachable";
      version = "1.0.0";
      authors = [ "Jonathan Reem <jonathan.reem@gmail.com>" ];
      sha256 = "1am8czbk5wwr25gbp2zr007744fxjshhdqjz9liz7wl4pnv3whcf";
      inherit dependencies buildDependencies features;
    };
    url_1_6_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "url";
      version = "1.6.0";
      authors = [ "The rust-url developers" ];
      sha256 = "1bvzl4dvjj84h46ai3x23wyafa2wwhchj08vr2brf25dxwc7mg18";
      inherit dependencies buildDependencies features;
    };
    utf8_ranges_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "utf8-ranges";
      version = "0.1.3";
      authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
      sha256 = "1cj548a91a93j8375p78qikaiam548xh84cb0ck8y119adbmsvbp";
      inherit dependencies buildDependencies features;
    };
    utf8_ranges_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "utf8-ranges";
      version = "1.0.0";
      authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
      sha256 = "0rzmqprwjv9yp1n0qqgahgm24872x6c0xddfym5pfndy7a36vkn0";
      inherit dependencies buildDependencies features;
    };
    vcpkg_0_2_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "vcpkg";
      version = "0.2.2";
      authors = [ "Jim McGrath <jimmc2@gmail.com>" ];
      sha256 = "1fl5j0ksnwrnsrf1b1a9lqbjgnajdipq0030vsbhx81mb7d9478a";
      inherit dependencies buildDependencies features;
    };
    void_1_0_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "void";
      version = "1.0.2";
      authors = [ "Jonathan Reem <jonathan.reem@gmail.com>" ];
      sha256 = "0h1dm0dx8dhf56a83k68mijyxigqhizpskwxfdrs1drwv2cdclv3";
      inherit dependencies buildDependencies features;
    };
    winapi_0_2_8_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "winapi";
      version = "0.2.8";
      authors = [ "Peter Atashian <retep998@gmail.com>" ];
      sha256 = "0a45b58ywf12vb7gvj6h3j264nydynmzyqz8d8rqxsj6icqv82as";
      inherit dependencies buildDependencies features;
    };
    winapi_build_0_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "winapi-build";
      version = "0.1.1";
      authors = [ "Peter Atashian <retep998@gmail.com>" ];
      sha256 = "1lxlpi87rkhxcwp2ykf1ldw3p108hwm24nywf3jfrvmff4rjhqga";
      libName = "build";
      inherit dependencies buildDependencies features;
    };
    ws2_32_sys_0_2_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
      crateName = "ws2_32-sys";
      version = "0.2.1";
      authors = [ "Peter Atashian <retep998@gmail.com>" ];
      sha256 = "1zpy9d9wk11sj17fczfngcj28w4xxjs3b4n036yzpy38dxp4f7kc";
      libName = "ws2_32";
      build = "build.rs";
      inherit dependencies buildDependencies features;
    };

in
rec {
  advapi32_sys_0_2_0 = advapi32_sys_0_2_0_ {
    dependencies = [ winapi_0_2_8 ];
    buildDependencies = [ winapi_build_0_1_1 ];
  };
  aho_corasick_0_5_3 = aho_corasick_0_5_3_ {
    dependencies = [ memchr_0_1_11 ];
  };
  aho_corasick_0_6_4 = aho_corasick_0_6_4_ {
    dependencies = [ memchr_2_0_1 ];
  };
  amq_proto_0_1_0 = amq_proto_0_1_0_ {
    dependencies = [ bit_vec_0_4_4 byteorder_0_5_3 enum_primitive_0_1_1 env_logger_0_3_5 error_chain_0_10_0 log_0_3_8 ];
  };
  amqp_0_1_0 = amqp_0_1_0_ {
    dependencies = [ amq_proto_0_1_0 env_logger_0_3_5 log_0_3_8 openssl_0_9_22 url_1_6_0 ];
    features = [ "openssl" "tls" ];
  };
  backtrace_0_3_4 = backtrace_0_3_4_ {
    dependencies = [ cfg_if_0_1_2 rustc_demangle_0_1_5 ]
      ++ (if (kernel == "linux" || kernel == "darwin") && !(kernel == "fuchsia") && !(kernel == "emscripten") && !(kernel == "darwin") && !(kernel == "ios") then [ backtrace_sys_0_1_16 ] else [])
      ++ (if (kernel == "linux" || kernel == "darwin") then [ libc_0_2_34 ] else [])
      ++ (if kernel == "windows" then [ dbghelp_sys_0_2_0 kernel32_sys_0_2_2 winapi_0_2_8 ] else []);
    features = [ "backtrace-sys" "coresymbolication" "dbghelp" "dbghelp-sys" "dladdr" "kernel32-sys" "libbacktrace" "libunwind" "winapi" ];
  };
  backtrace_sys_0_1_16 = backtrace_sys_0_1_16_ {
    dependencies = [ libc_0_2_34 ];
    buildDependencies = [ cc_1_0_3 ];
  };
  bit_vec_0_4_4 = bit_vec_0_4_4_ {};
  bitflags_0_7_0 = bitflags_0_7_0_ {};
  bitflags_0_9_1 = bitflags_0_9_1_ {
    features = [ "example_generated" ];
  };
  bufstream_0_1_3 = bufstream_0_1_3_ {};
  byteorder_0_5_3 = byteorder_0_5_3_ {
    features = [ "std" ];
  };
  byteorder_1_2_1 = byteorder_1_2_1_ {
    features = [ "std" ];
  };
  bytes_0_4_5 = bytes_0_4_5_ {
    dependencies = [ byteorder_1_2_1 iovec_0_1_1 ];
  };
  cc_1_0_3 = cc_1_0_3_ {
    dependencies = [];
  };
  cfg_if_0_1_2 = cfg_if_0_1_2_ {};
  chrono_0_4_0 = chrono_0_4_0_ {
    dependencies = [ num_0_1_41 time_0_1_38 ];
  };
  core_foundation_0_2_3 = core_foundation_0_2_3_ {
    dependencies = [ core_foundation_sys_0_2_3 libc_0_2_34 ];
  };
  core_foundation_sys_0_2_3 = core_foundation_sys_0_2_3_ {
    dependencies = [ libc_0_2_34 ];
  };
  crypt32_sys_0_2_0 = crypt32_sys_0_2_0_ {
    dependencies = [ winapi_0_2_8 ];
    buildDependencies = [ winapi_build_0_1_1 ];
  };
  dbghelp_sys_0_2_0 = dbghelp_sys_0_2_0_ {
    dependencies = [ winapi_0_2_8 ];
    buildDependencies = [ winapi_build_0_1_1 ];
  };
  dtoa_0_4_2 = dtoa_0_4_2_ {};
  encoding_0_2_33 = encoding_0_2_33_ {
    dependencies = [ encoding_index_japanese_1_20141219_5 encoding_index_korean_1_20141219_5 encoding_index_simpchinese_1_20141219_5 encoding_index_singlebyte_1_20141219_5 encoding_index_tradchinese_1_20141219_5 ];
  };
  encoding_index_japanese_1_20141219_5 = encoding_index_japanese_1_20141219_5_ {
    dependencies = [ encoding_index_tests_0_1_4 ];
  };
  encoding_index_korean_1_20141219_5 = encoding_index_korean_1_20141219_5_ {
    dependencies = [ encoding_index_tests_0_1_4 ];
  };
  encoding_index_simpchinese_1_20141219_5 = encoding_index_simpchinese_1_20141219_5_ {
    dependencies = [ encoding_index_tests_0_1_4 ];
  };
  encoding_index_singlebyte_1_20141219_5 = encoding_index_singlebyte_1_20141219_5_ {
    dependencies = [ encoding_index_tests_0_1_4 ];
  };
  encoding_index_tradchinese_1_20141219_5 = encoding_index_tradchinese_1_20141219_5_ {
    dependencies = [ encoding_index_tests_0_1_4 ];
  };
  encoding_index_tests_0_1_4 = encoding_index_tests_0_1_4_ {};
  enum_primitive_0_1_1 = enum_primitive_0_1_1_ {
    dependencies = [ num_traits_0_1_41 ];
  };
  env_logger_0_3_5 = env_logger_0_3_5_ {
    dependencies = [ log_0_3_8 regex_0_1_80 ];
    features = [ "regex" ];
  };
  env_logger_0_4_3 = env_logger_0_4_3_ {
    dependencies = [ log_0_3_8 regex_0_2_3 ];
    features = [ "regex" ];
  };
  error_chain_0_10_0 = error_chain_0_10_0_ {
    dependencies = [ backtrace_0_3_4 ];
    features = [ "backtrace" "example_generated" ];
  };
  foreign_types_0_3_2 = foreign_types_0_3_2_ {
    dependencies = [ foreign_types_shared_0_1_1 ];
  };
  foreign_types_shared_0_1_1 = foreign_types_shared_0_1_1_ {};
  fuchsia_zircon_0_2_1 = fuchsia_zircon_0_2_1_ {
    dependencies = [ fuchsia_zircon_sys_0_2_0 ];
  };
  fuchsia_zircon_sys_0_2_0 = fuchsia_zircon_sys_0_2_0_ {
    dependencies = [ bitflags_0_7_0 ];
  };
  futures_0_1_17 = futures_0_1_17_ {
    features = [ "use_std" "with-deprecated" ];
  };
  idna_0_1_4 = idna_0_1_4_ {
    dependencies = [ matches_0_1_6 unicode_bidi_0_3_4 unicode_normalization_0_1_5 ];
  };
  iovec_0_1_1 = iovec_0_1_1_ {
    dependencies = (if (kernel == "linux" || kernel == "darwin") then [ libc_0_2_34 ] else [])
      ++ (if kernel == "windows" then [ winapi_0_2_8 ] else []);
  };
  irc_0_12_5 = irc_0_12_5_ {
    dependencies = [ bufstream_0_1_3 bytes_0_4_5 chrono_0_4_0 encoding_0_2_33 error_chain_0_10_0 futures_0_1_17 native_tls_0_1_4 serde_1_0_23 serde_derive_1_0_23 serde_json_1_0_7 tokio_core_0_1_10 tokio_io_0_1_4 tokio_mockstream_1_1_0 tokio_timer_0_1_2 tokio_tls_0_1_3 toml_0_4_5 ];
    features = [ "ctcp" "json" "serde_json" "toml" ];
  };
  ircbot_0_1_0 = ircbot_0_1_0_ {
    dependencies = [ amqp_0_1_0 env_logger_0_4_3 irc_0_12_5 log_0_3_8 serde_1_0_23 serde_derive_1_0_23 serde_json_1_0_7 toml_0_4_5 ];
  };
  itoa_0_3_4 = itoa_0_3_4_ {};
  kernel32_sys_0_2_2 = kernel32_sys_0_2_2_ {
    dependencies = [ winapi_0_2_8 ];
    buildDependencies = [ winapi_build_0_1_1 ];
  };
  lazy_static_0_2_11 = lazy_static_0_2_11_ {};
  lazy_static_1_0_0 = lazy_static_1_0_0_ {
    dependencies = [];
  };
  lazycell_0_5_1 = lazycell_0_5_1_ {};
  libc_0_2_34 = libc_0_2_34_ {
    features = [ "use_std" ];
  };
  log_0_3_8 = log_0_3_8_ {
    features = [ "use_std" ];
  };
  matches_0_1_6 = matches_0_1_6_ {};
  memchr_0_1_11 = memchr_0_1_11_ {
    dependencies = [ libc_0_2_34 ];
  };
  memchr_2_0_1 = memchr_2_0_1_ {
    dependencies = [ libc_0_2_34 ];
    features = [ "libc" "use_std" ];
  };
  mio_0_6_11 = mio_0_6_11_ {
    dependencies = [ iovec_0_1_1 lazycell_0_5_1 log_0_3_8 net2_0_2_31 slab_0_3_0 ]
      ++ (if kernel == "fuchsia" then [ fuchsia_zircon_0_2_1 fuchsia_zircon_sys_0_2_0 ] else [])
      ++ (if (kernel == "linux" || kernel == "darwin") then [ libc_0_2_34 ] else [])
      ++ (if kernel == "windows" then [ kernel32_sys_0_2_2 miow_0_2_1 winapi_0_2_8 ] else []);
    features = [ "with-deprecated" ];
  };
  miow_0_2_1 = miow_0_2_1_ {
    dependencies = [ kernel32_sys_0_2_2 net2_0_2_31 winapi_0_2_8 ws2_32_sys_0_2_1 ];
  };
  native_tls_0_1_4 = native_tls_0_1_4_ {
    dependencies = (if !(kernel == "windows" || kernel == "darwin") then [ openssl_0_9_22 ] else [])
      ++ (if kernel == "darwin" then [ (security_framework_0_1_16.override { features = [ "OSX_10_8" ]; }) security_framework_sys_0_1_16 tempdir_0_3_5 ] else [])
      ++ (if kernel == "windows" then [ schannel_0_1_9 ] else []);
  };
  net2_0_2_31 = net2_0_2_31_ {
    dependencies = [ cfg_if_0_1_2 ]
      ++ (if (kernel == "linux" || kernel == "darwin") then [ libc_0_2_34 ] else [])
      ++ (if kernel == "windows" then [ kernel32_sys_0_2_2 winapi_0_2_8 ws2_32_sys_0_2_1 ] else [])
      ++ (if kernel == "i686-apple-darwin" then [ libc_0_2_34 ] else [])
      ++ (if kernel == "i686-unknown-linux-gnu" then [ libc_0_2_34 ] else [])
      ++ (if kernel == "x86_64-apple-darwin" then [ libc_0_2_34 ] else [])
      ++ (if kernel == "x86_64-unknown-linux-gnu" then [ libc_0_2_34 ] else []);
    features = [ "duration" ];
  };
  num_0_1_41 = num_0_1_41_ {
    dependencies = [ num_integer_0_1_35 num_iter_0_1_34 num_traits_0_1_41 ];
    features = [ "bigint" "complex" "rational" "rustc-serialize" ];
  };
  num_integer_0_1_35 = num_integer_0_1_35_ {
    dependencies = [ num_traits_0_1_41 ];
  };
  num_iter_0_1_34 = num_iter_0_1_34_ {
    dependencies = [ num_integer_0_1_35 num_traits_0_1_41 ];
  };
  num_traits_0_1_41 = num_traits_0_1_41_ {};
  openssl_0_9_22 = openssl_0_9_22_ {
    dependencies = [ bitflags_0_9_1 foreign_types_0_3_2 lazy_static_0_2_11 libc_0_2_34 openssl_sys_0_9_22 ];
  };
  openssl_sys_0_9_22 = openssl_sys_0_9_22_ {
    dependencies = [ libc_0_2_34 ]
      ++ (if abi == "msvc" then [] else []);
    buildDependencies = [ cc_1_0_3 pkg_config_0_3_9 ];
  };
  percent_encoding_1_0_1 = percent_encoding_1_0_1_ {};
  pkg_config_0_3_9 = pkg_config_0_3_9_ {};
  quote_0_3_15 = quote_0_3_15_ {};
  rand_0_3_18 = rand_0_3_18_ {
    dependencies = [ libc_0_2_34 ]
      ++ (if kernel == "fuchsia" then [ fuchsia_zircon_0_2_1 ] else []);
  };
  redox_syscall_0_1_32 = redox_syscall_0_1_32_ {};
  regex_0_1_80 = regex_0_1_80_ {
    dependencies = [ aho_corasick_0_5_3 memchr_0_1_11 regex_syntax_0_3_9 thread_local_0_2_7 utf8_ranges_0_1_3 ];
  };
  regex_0_2_3 = regex_0_2_3_ {
    dependencies = [ aho_corasick_0_6_4 memchr_2_0_1 regex_syntax_0_4_1 thread_local_0_3_4 utf8_ranges_1_0_0 ];
  };
  regex_syntax_0_3_9 = regex_syntax_0_3_9_ {};
  regex_syntax_0_4_1 = regex_syntax_0_4_1_ {};
  rustc_demangle_0_1_5 = rustc_demangle_0_1_5_ {};
  schannel_0_1_9 = schannel_0_1_9_ {
    dependencies = [ advapi32_sys_0_2_0 crypt32_sys_0_2_0 kernel32_sys_0_2_2 lazy_static_1_0_0 secur32_sys_0_2_0 winapi_0_2_8 ];
    buildDependencies = [ winapi_build_0_1_1 ];
  };
  scoped_tls_0_1_0 = scoped_tls_0_1_0_ {};
  secur32_sys_0_2_0 = secur32_sys_0_2_0_ {
    dependencies = [ winapi_0_2_8 ];
    buildDependencies = [ winapi_build_0_1_1 ];
  };
  security_framework_0_1_16 = security_framework_0_1_16_ {
    dependencies = [ core_foundation_0_2_3 core_foundation_sys_0_2_3 libc_0_2_34 security_framework_sys_0_1_16 ];
  };
  security_framework_sys_0_1_16 = security_framework_sys_0_1_16_ {
    dependencies = [ core_foundation_sys_0_2_3 libc_0_2_34 ];
  };
  serde_1_0_23 = serde_1_0_23_ {
    features = [ "std" ];
  };
  serde_derive_1_0_23 = serde_derive_1_0_23_ {
    dependencies = [ quote_0_3_15 serde_derive_internals_0_17_0 (syn_0_11_11.override { features = [ "visit" ]; }) ];
  };
  serde_derive_internals_0_17_0 = serde_derive_internals_0_17_0_ {
    dependencies = [ (syn_0_11_11.override { features = [ "parsing" ]; }) synom_0_11_3 ];
  };
  serde_json_1_0_7 = serde_json_1_0_7_ {
    dependencies = [ dtoa_0_4_2 itoa_0_3_4 num_traits_0_1_41 serde_1_0_23 ];
  };
  slab_0_3_0 = slab_0_3_0_ {};
  slab_0_4_0 = slab_0_4_0_ {};
  syn_0_11_11 = syn_0_11_11_ {
    dependencies = [ quote_0_3_15 synom_0_11_3 unicode_xid_0_0_4 ];
    features = [ "parsing" "printing" "quote" "synom" "unicode-xid" "visit" ];
  };
  synom_0_11_3 = synom_0_11_3_ {
    dependencies = [ unicode_xid_0_0_4 ];
  };
  tempdir_0_3_5 = tempdir_0_3_5_ {
    dependencies = [ rand_0_3_18 ];
  };
  thread_id_2_0_0 = thread_id_2_0_0_ {
    dependencies = [ kernel32_sys_0_2_2 libc_0_2_34 ];
  };
  thread_local_0_2_7 = thread_local_0_2_7_ {
    dependencies = [ thread_id_2_0_0 ];
  };
  thread_local_0_3_4 = thread_local_0_3_4_ {
    dependencies = [ lazy_static_0_2_11 unreachable_1_0_0 ];
  };
  time_0_1_38 = time_0_1_38_ {
    dependencies = [ libc_0_2_34 ]
      ++ (if kernel == "redox" then [ redox_syscall_0_1_32 ] else [])
      ++ (if kernel == "windows" then [ kernel32_sys_0_2_2 winapi_0_2_8 ] else []);
  };
  tokio_core_0_1_10 = tokio_core_0_1_10_ {
    dependencies = [ bytes_0_4_5 futures_0_1_17 iovec_0_1_1 log_0_3_8 mio_0_6_11 scoped_tls_0_1_0 slab_0_4_0 tokio_io_0_1_4 ];
  };
  tokio_io_0_1_4 = tokio_io_0_1_4_ {
    dependencies = [ bytes_0_4_5 futures_0_1_17 log_0_3_8 ];
  };
  tokio_mockstream_1_1_0 = tokio_mockstream_1_1_0_ {
    dependencies = [ futures_0_1_17 tokio_io_0_1_4 ];
  };
  tokio_timer_0_1_2 = tokio_timer_0_1_2_ {
    dependencies = [ futures_0_1_17 slab_0_3_0 ];
  };
  tokio_tls_0_1_3 = tokio_tls_0_1_3_ {
    dependencies = [ futures_0_1_17 native_tls_0_1_4 tokio_core_0_1_10 tokio_io_0_1_4 ]
      ++ (if !(kernel == "darwin") && !(kernel == "windows") && !(kernel == "ios") then [] else [])
      ++ (if kernel == "darwin" || kernel == "ios" then [] else [])
      ++ (if kernel == "windows" then [] else []);
  };
  toml_0_4_5 = toml_0_4_5_ {
    dependencies = [ serde_1_0_23 ];
  };
  unicode_bidi_0_3_4 = unicode_bidi_0_3_4_ {
    dependencies = [ matches_0_1_6 ];
  };
  unicode_normalization_0_1_5 = unicode_normalization_0_1_5_ {};
  unicode_xid_0_0_4 = unicode_xid_0_0_4_ {};
  unreachable_1_0_0 = unreachable_1_0_0_ {
    dependencies = [ void_1_0_2 ];
  };
  url_1_6_0 = url_1_6_0_ {
    dependencies = [ idna_0_1_4 matches_0_1_6 percent_encoding_1_0_1 ];
  };
  utf8_ranges_0_1_3 = utf8_ranges_0_1_3_ {};
  utf8_ranges_1_0_0 = utf8_ranges_1_0_0_ {};
  vcpkg_0_2_2 = vcpkg_0_2_2_ {};
  void_1_0_2 = void_1_0_2_ {
    features = [ "std" ];
  };
  winapi_0_2_8 = winapi_0_2_8_ {};
  winapi_build_0_1_1 = winapi_build_0_1_1_ {};
  ws2_32_sys_0_2_1 = ws2_32_sys_0_2_1_ {
    dependencies = [ winapi_0_2_8 ];
    buildDependencies = [ winapi_build_0_1_1 ];
  };
}
