[package]
name = "ofborg-send-event"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
hmac = "0.13"
reqwest = { version = "0.13", features = ["json"] }
sha2 = "0.11"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
serde_json = "1.0.135"
tracing = "0.1.41"

octocrab = { version = "0.51.0", default-features = false, features = [
  "default-client",
  "follow-redirect",
  "jwt-rust-crypto",
  "retry",
  "rustls",
  # Enabling `rustls-ring` leads to runtime panics: https://github.com/XAMPPRocky/octocrab/issues/855
  # "rustls-ring",
  "timeout",
  "tracing",
] }
ofborg = { path = "../ofborg" }
