# Generated by carnix 0.10.0: carnix generate-nix --src .
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO // rec {
# amqp-0.1.0

    crates.amqp."0.1.0" = deps: { features?(features_.amqp."0.1.0" deps {}) }: buildRustCrate {
      crateName = "amqp";
      version = "0.1.0";
      description = "AMQP/RabbitMQ protocol client";
      authors = [ "Andrii Dmytrenko <andrey@reevoo.com>" ];
      src = fetchgit {
         url = "https://github.com/grahamc/rust-amqp.git";
         rev = "f9aec2f40aef69a459f26003ce47048f8e2a08d1";
         sha256 = "09k6fl7l0rcwilnckdfv3smiv1ilrwi1jxmrrkjwbrj64lky3jdy";
         fetchSubmodules = false;
      };
      dependencies = mapFeatures features ([
        (cratesIO.crates."amq_proto"."${deps."amqp"."0.1.0"."amq_proto"}" deps)
        (cratesIO.crates."env_logger"."${deps."amqp"."0.1.0"."env_logger"}" deps)
        (cratesIO.crates."log"."${deps."amqp"."0.1.0"."log"}" deps)
        (cratesIO.crates."time"."${deps."amqp"."0.1.0"."time"}" deps)
        (cratesIO.crates."url"."${deps."amqp"."0.1.0"."url"}" deps)
      ]
        ++ (if features.amqp."0.1.0".openssl or false then [ (cratesIO.crates.openssl."${deps."amqp"."0.1.0".openssl}" deps) ] else []));
      features = mkFeatures (features."amqp"."0.1.0" or {});
    };
    features_.amqp."0.1.0" = deps: f: updateFeatures f (rec {
      amq_proto."${deps.amqp."0.1.0".amq_proto}".default = true;
      amqp = fold recursiveUpdate {} [
        { "0.1.0"."openssl" =
          (f.amqp."0.1.0"."openssl" or false) ||
          (f.amqp."0.1.0".tls or false) ||
          (amqp."0.1.0"."tls" or false); }
        { "0.1.0"."tls" =
          (f.amqp."0.1.0"."tls" or false) ||
          (f.amqp."0.1.0".default or false) ||
          (amqp."0.1.0"."default" or false); }
        { "0.1.0".default = (f.amqp."0.1.0".default or true); }
      ];
      env_logger."${deps.amqp."0.1.0".env_logger}".default = true;
      log."${deps.amqp."0.1.0".log}".default = true;
      openssl."${deps.amqp."0.1.0".openssl}".default = true;
      time."${deps.amqp."0.1.0".time}".default = true;
      url."${deps.amqp."0.1.0".url}".default = true;
    }) [
      (cratesIO.features_.amq_proto."${deps."amqp"."0.1.0"."amq_proto"}" deps)
      (cratesIO.features_.env_logger."${deps."amqp"."0.1.0"."env_logger"}" deps)
      (cratesIO.features_.log."${deps."amqp"."0.1.0"."log"}" deps)
      (cratesIO.features_.openssl."${deps."amqp"."0.1.0"."openssl"}" deps)
      (cratesIO.features_.time."${deps."amqp"."0.1.0"."time"}" deps)
      (cratesIO.features_.url."${deps."amqp"."0.1.0"."url"}" deps)
    ];


# end
# hubcaps-0.3.16

    crates.hubcaps."0.3.16" = deps: { features?(features_.hubcaps."0.3.16" deps {}) }: buildRustCrate {
      crateName = "hubcaps";
      version = "0.3.16";
      description = "Rust interface for Github";
      authors = [ "softprops <d.tangren@gmail.com>" ];
      src = fetchgit {
         url = "https://github.com/grahamc/hubcaps.git";
         rev = "5e656ba35ab4ee74aa72b3b5c3a62e1bf351ff6a";
         sha256 = "1p7rn8y71fjwfag65437gz7a56pysz9n69smaknvblyxpjdzmh4d";
         fetchSubmodules = false;
      };
      dependencies = mapFeatures features ([
        (cratesIO.crates."error_chain"."${deps."hubcaps"."0.3.16"."error_chain"}" deps)
        (cratesIO.crates."frank_jwt"."${deps."hubcaps"."0.3.16"."frank_jwt"}" deps)
        (cratesIO.crates."hyper"."${deps."hubcaps"."0.3.16"."hyper"}" deps)
        (cratesIO.crates."log"."${deps."hubcaps"."0.3.16"."log"}" deps)
        (cratesIO.crates."serde"."${deps."hubcaps"."0.3.16"."serde"}" deps)
        (cratesIO.crates."serde_derive"."${deps."hubcaps"."0.3.16"."serde_derive"}" deps)
        (cratesIO.crates."serde_json"."${deps."hubcaps"."0.3.16"."serde_json"}" deps)
        (cratesIO.crates."url"."${deps."hubcaps"."0.3.16"."url"}" deps)
      ]);
    };
    features_.hubcaps."0.3.16" = deps: f: updateFeatures f (rec {
      error_chain."${deps.hubcaps."0.3.16".error_chain}".default = true;
      frank_jwt."${deps.hubcaps."0.3.16".frank_jwt}".default = true;
      hubcaps."0.3.16".default = (f.hubcaps."0.3.16".default or true);
      hyper."${deps.hubcaps."0.3.16".hyper}".default = true;
      log."${deps.hubcaps."0.3.16".log}".default = true;
      serde."${deps.hubcaps."0.3.16".serde}".default = true;
      serde_derive."${deps.hubcaps."0.3.16".serde_derive}".default = true;
      serde_json."${deps.hubcaps."0.3.16".serde_json}".default = true;
      url."${deps.hubcaps."0.3.16".url}".default = true;
    }) [
      (cratesIO.features_.error_chain."${deps."hubcaps"."0.3.16"."error_chain"}" deps)
      (cratesIO.features_.frank_jwt."${deps."hubcaps"."0.3.16"."frank_jwt"}" deps)
      (cratesIO.features_.hyper."${deps."hubcaps"."0.3.16"."hyper"}" deps)
      (cratesIO.features_.log."${deps."hubcaps"."0.3.16"."log"}" deps)
      (cratesIO.features_.serde."${deps."hubcaps"."0.3.16"."serde"}" deps)
      (cratesIO.features_.serde_derive."${deps."hubcaps"."0.3.16"."serde_derive"}" deps)
      (cratesIO.features_.serde_json."${deps."hubcaps"."0.3.16"."serde_json"}" deps)
      (cratesIO.features_.url."${deps."hubcaps"."0.3.16"."url"}" deps)
    ];


# end
# ofborg-0.1.8

    crates.ofborg."0.1.8" = deps: { features?(features_.ofborg."0.1.8" deps {}) }: buildRustCrate {
      crateName = "ofborg";
      version = "0.1.8";
      authors = [ "Graham Christensen <graham@grahamc.com>" ];
      edition = "2018";
      src = include [ "Cargo.toml" "ofborg" ] ./.;
      workspace_member = "ofborg";
      build = "build.rs";
      dependencies = mapFeatures features ([
        (crates."amqp"."${deps."ofborg"."0.1.8"."amqp"}" deps)
        (cratesIO.crates."chrono"."${deps."ofborg"."0.1.8"."chrono"}" deps)
        (cratesIO.crates."either"."${deps."ofborg"."0.1.8"."either"}" deps)
        (cratesIO.crates."env_logger"."${deps."ofborg"."0.1.8"."env_logger"}" deps)
        (cratesIO.crates."fs2"."${deps."ofborg"."0.1.8"."fs2"}" deps)
        (crates."hubcaps"."${deps."ofborg"."0.1.8"."hubcaps"}" deps)
        (cratesIO.crates."hyper"."${deps."ofborg"."0.1.8"."hyper"}" deps)
        (cratesIO.crates."hyper_native_tls"."${deps."ofborg"."0.1.8"."hyper_native_tls"}" deps)
        (cratesIO.crates."log"."${deps."ofborg"."0.1.8"."log"}" deps)
        (cratesIO.crates."lru_cache"."${deps."ofborg"."0.1.8"."lru_cache"}" deps)
        (cratesIO.crates."md5"."${deps."ofborg"."0.1.8"."md5"}" deps)
        (cratesIO.crates."nom"."${deps."ofborg"."0.1.8"."nom"}" deps)
        (cratesIO.crates."separator"."${deps."ofborg"."0.1.8"."separator"}" deps)
        (cratesIO.crates."serde"."${deps."ofborg"."0.1.8"."serde"}" deps)
        (cratesIO.crates."serde_derive"."${deps."ofborg"."0.1.8"."serde_derive"}" deps)
        (cratesIO.crates."serde_json"."${deps."ofborg"."0.1.8"."serde_json"}" deps)
        (cratesIO.crates."sys_info"."${deps."ofborg"."0.1.8"."sys_info"}" deps)
        (cratesIO.crates."tempfile"."${deps."ofborg"."0.1.8"."tempfile"}" deps)
        (cratesIO.crates."uuid"."${deps."ofborg"."0.1.8"."uuid"}" deps)
      ]);
    };
    features_.ofborg."0.1.8" = deps: f: updateFeatures f (rec {
      amqp."${deps.ofborg."0.1.8".amqp}".default = true;
      chrono."${deps.ofborg."0.1.8".chrono}".default = true;
      either."${deps.ofborg."0.1.8".either}".default = true;
      env_logger."${deps.ofborg."0.1.8".env_logger}".default = true;
      fs2."${deps.ofborg."0.1.8".fs2}".default = true;
      hubcaps."${deps.ofborg."0.1.8".hubcaps}".default = true;
      hyper."${deps.ofborg."0.1.8".hyper}".default = true;
      hyper_native_tls."${deps.ofborg."0.1.8".hyper_native_tls}".default = true;
      log."${deps.ofborg."0.1.8".log}".default = true;
      lru_cache."${deps.ofborg."0.1.8".lru_cache}".default = true;
      md5."${deps.ofborg."0.1.8".md5}".default = true;
      nom."${deps.ofborg."0.1.8".nom}".default = true;
      ofborg."0.1.8".default = (f.ofborg."0.1.8".default or true);
      separator."${deps.ofborg."0.1.8".separator}".default = true;
      serde."${deps.ofborg."0.1.8".serde}".default = true;
      serde_derive."${deps.ofborg."0.1.8".serde_derive}".default = true;
      serde_json."${deps.ofborg."0.1.8".serde_json}".default = true;
      sys_info."${deps.ofborg."0.1.8".sys_info}".default = true;
      tempfile."${deps.ofborg."0.1.8".tempfile}".default = true;
      uuid = fold recursiveUpdate {} [
        { "${deps.ofborg."0.1.8".uuid}"."v4" = true; }
        { "${deps.ofborg."0.1.8".uuid}".default = true; }
      ];
    }) [
      (features_.amqp."${deps."ofborg"."0.1.8"."amqp"}" deps)
      (cratesIO.features_.chrono."${deps."ofborg"."0.1.8"."chrono"}" deps)
      (cratesIO.features_.either."${deps."ofborg"."0.1.8"."either"}" deps)
      (cratesIO.features_.env_logger."${deps."ofborg"."0.1.8"."env_logger"}" deps)
      (cratesIO.features_.fs2."${deps."ofborg"."0.1.8"."fs2"}" deps)
      (features_.hubcaps."${deps."ofborg"."0.1.8"."hubcaps"}" deps)
      (cratesIO.features_.hyper."${deps."ofborg"."0.1.8"."hyper"}" deps)
      (cratesIO.features_.hyper_native_tls."${deps."ofborg"."0.1.8"."hyper_native_tls"}" deps)
      (cratesIO.features_.log."${deps."ofborg"."0.1.8"."log"}" deps)
      (cratesIO.features_.lru_cache."${deps."ofborg"."0.1.8"."lru_cache"}" deps)
      (cratesIO.features_.md5."${deps."ofborg"."0.1.8"."md5"}" deps)
      (cratesIO.features_.nom."${deps."ofborg"."0.1.8"."nom"}" deps)
      (cratesIO.features_.separator."${deps."ofborg"."0.1.8"."separator"}" deps)
      (cratesIO.features_.serde."${deps."ofborg"."0.1.8"."serde"}" deps)
      (cratesIO.features_.serde_derive."${deps."ofborg"."0.1.8"."serde_derive"}" deps)
      (cratesIO.features_.serde_json."${deps."ofborg"."0.1.8"."serde_json"}" deps)
      (cratesIO.features_.sys_info."${deps."ofborg"."0.1.8"."sys_info"}" deps)
      (cratesIO.features_.tempfile."${deps."ofborg"."0.1.8"."tempfile"}" deps)
      (cratesIO.features_.uuid."${deps."ofborg"."0.1.8"."uuid"}" deps)
    ];


# end
# ofborg-simple-build-0.1.0

    crates.ofborg_simple_build."0.1.0" = deps: { features?(features_.ofborg_simple_build."0.1.0" deps {}) }: buildRustCrate {
      crateName = "ofborg-simple-build";
      version = "0.1.0";
      authors = [ "Daiderd Jordan <daiderd@gmail.com>" ];
      edition = "2018";
      src = include [ "Cargo.toml" "ofborg-simple-build" ] ./.;
      workspace_member = "ofborg-simple-build";
      dependencies = mapFeatures features ([
        (cratesIO.crates."log"."${deps."ofborg_simple_build"."0.1.0"."log"}" deps)
        (crates."ofborg"."${deps."ofborg_simple_build"."0.1.0"."ofborg"}" deps)
      ]);
    };
    features_.ofborg_simple_build."0.1.0" = deps: f: updateFeatures f (rec {
      log."${deps.ofborg_simple_build."0.1.0".log}".default = true;
      ofborg."${deps.ofborg_simple_build."0.1.0".ofborg}".default = true;
      ofborg_simple_build."0.1.0".default = (f.ofborg_simple_build."0.1.0".default or true);
    }) [
      (cratesIO.features_.log."${deps."ofborg_simple_build"."0.1.0"."log"}" deps)
      (features_.ofborg."${deps."ofborg_simple_build"."0.1.0"."ofborg"}" deps)
    ];


# end

  };

  ofborg = crates.crates.ofborg."0.1.8" deps;
  ofborg_simple_build = crates.crates.ofborg_simple_build."0.1.0" deps;
  __all = [ (ofborg {}) (ofborg_simple_build {}) ];
  deps.aho_corasick."0.5.3" = {
    memchr = "0.1.11";
  };
  deps.aho_corasick."0.6.9" = {
    memchr = "2.1.2";
  };
  deps.amq_proto."0.1.0" = {
    bit_vec = "0.4.4";
    byteorder = "0.5.3";
    enum_primitive = "0.1.1";
    env_logger = "0.3.5";
    error_chain = "0.10.0";
    log = "0.3.8";
  };
  deps.amqp."0.1.0" = {
    amq_proto = "0.1.0";
    env_logger = "0.3.5";
    log = "0.3.8";
    openssl = "0.9.24";
    time = "0.1.41";
    url = "1.7.2";
  };
  deps.antidote."1.0.0" = {};
  deps.autocfg."0.1.1" = {};
  deps.backtrace."0.3.13" = {
    cfg_if = "0.1.6";
    rustc_demangle = "0.1.13";
    autocfg = "0.1.1";
    backtrace_sys = "0.1.28";
    libc = "0.2.46";
    winapi = "0.3.6";
  };
  deps.backtrace_sys."0.1.28" = {
    libc = "0.2.46";
    cc = "1.0.28";
  };
  deps.base64."0.9.3" = {
    byteorder = "1.2.7";
    safemem = "0.3.0";
  };
  deps.base64."0.10.0" = {
    byteorder = "1.2.7";
  };
  deps.bit_vec."0.4.4" = {};
  deps.bitflags."0.9.1" = {};
  deps.bitflags."1.0.4" = {};
  deps.byteorder."0.5.3" = {};
  deps.byteorder."1.2.7" = {};
  deps.cc."1.0.28" = {};
  deps.cfg_if."0.1.6" = {};
  deps.chrono."0.4.6" = {
    num_integer = "0.1.39";
    num_traits = "0.2.6";
    time = "0.1.41";
  };
  deps.core_foundation."0.2.3" = {
    core_foundation_sys = "0.2.3";
    libc = "0.2.46";
  };
  deps.core_foundation_sys."0.2.3" = {
    libc = "0.2.46";
  };
  deps.either."1.5.0" = {};
  deps.enum_primitive."0.1.1" = {
    num_traits = "0.1.43";
  };
  deps.env_logger."0.3.5" = {
    log = "0.3.8";
    regex = "0.1.80";
  };
  deps.env_logger."0.4.3" = {
    log = "0.3.8";
    regex = "0.2.11";
  };
  deps.error_chain."0.10.0" = {
    backtrace = "0.3.13";
  };
  deps.foreign_types."0.3.2" = {
    foreign_types_shared = "0.1.1";
  };
  deps.foreign_types_shared."0.1.1" = {};
  deps.frank_jwt."3.1.0" = {
    base64 = "0.10.0";
    openssl = "0.10.16";
    serde = "1.0.84";
    serde_json = "1.0.34";
  };
  deps.fs2."0.4.3" = {
    libc = "0.2.46";
    winapi = "0.3.6";
  };
  deps.fuchsia_zircon."0.3.3" = {
    bitflags = "1.0.4";
    fuchsia_zircon_sys = "0.3.3";
  };
  deps.fuchsia_zircon_sys."0.3.3" = {};
  deps.httparse."1.3.3" = {};
  deps.hubcaps."0.3.16" = {
    error_chain = "0.10.0";
    frank_jwt = "3.1.0";
    hyper = "0.10.15";
    log = "0.3.8";
    serde = "1.0.84";
    serde_derive = "1.0.84";
    serde_json = "1.0.34";
    url = "1.7.2";
  };
  deps.hyper."0.10.15" = {
    base64 = "0.9.3";
    httparse = "1.3.3";
    language_tags = "0.2.2";
    log = "0.3.8";
    mime = "0.2.6";
    num_cpus = "1.9.0";
    time = "0.1.41";
    traitobject = "0.1.0";
    typeable = "0.1.2";
    unicase = "1.4.2";
    url = "1.7.2";
  };
  deps.hyper_native_tls."0.2.4" = {
    antidote = "1.0.0";
    hyper = "0.10.15";
    native_tls = "0.1.5";
  };
  deps.idna."0.1.5" = {
    matches = "0.1.8";
    unicode_bidi = "0.3.4";
    unicode_normalization = "0.1.7";
  };
  deps.itoa."0.4.3" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.language_tags."0.2.2" = {};
  deps.lazy_static."0.2.11" = {};
  deps.lazy_static."1.2.0" = {};
  deps.libc."0.2.46" = {};
  deps.linked_hash_map."0.4.2" = {};
  deps.log."0.3.8" = {};
  deps.lru_cache."0.1.1" = {
    linked_hash_map = "0.4.2";
  };
  deps.matches."0.1.8" = {};
  deps.md5."0.3.8" = {};
  deps.memchr."0.1.11" = {
    libc = "0.2.46";
  };
  deps.memchr."2.1.2" = {
    cfg_if = "0.1.6";
    libc = "0.2.46";
    version_check = "0.1.5";
  };
  deps.mime."0.2.6" = {
    log = "0.3.8";
  };
  deps.native_tls."0.1.5" = {
    lazy_static = "0.2.11";
    libc = "0.2.46";
    security_framework = "0.1.16";
    security_framework_sys = "0.1.16";
    tempdir = "0.3.7";
    openssl = "0.9.24";
    schannel = "0.1.14";
  };
  deps.nom."4.1.1" = {
    memchr = "2.1.2";
  };
  deps.num_integer."0.1.39" = {
    num_traits = "0.2.6";
  };
  deps.num_traits."0.1.43" = {
    num_traits = "0.2.6";
  };
  deps.num_traits."0.2.6" = {};
  deps.num_cpus."1.9.0" = {
    libc = "0.2.46";
  };
  deps.ofborg."0.1.8" = {
    amqp = "0.1.0";
    chrono = "0.4.6";
    either = "1.5.0";
    env_logger = "0.4.3";
    fs2 = "0.4.3";
    hubcaps = "0.3.16";
    hyper = "0.10.15";
    hyper_native_tls = "0.2.4";
    log = "0.3.8";
    lru_cache = "0.1.1";
    md5 = "0.3.8";
    nom = "4.1.1";
    separator = "0.4.1";
    serde = "1.0.84";
    serde_derive = "1.0.84";
    serde_json = "1.0.34";
    sys_info = "0.5.6";
    tempfile = "2.2.0";
    uuid = "0.4.0";
  };
  deps.ofborg_simple_build."0.1.0" = {
    log = "0.3.8";
    ofborg = "0.1.8";
  };
  deps.openssl."0.9.24" = {
    bitflags = "0.9.1";
    foreign_types = "0.3.2";
    lazy_static = "1.2.0";
    libc = "0.2.46";
    openssl_sys = "0.9.40";
  };
  deps.openssl."0.10.16" = {
    bitflags = "1.0.4";
    cfg_if = "0.1.6";
    foreign_types = "0.3.2";
    lazy_static = "1.2.0";
    libc = "0.2.46";
    openssl_sys = "0.9.40";
  };
  deps.openssl_sys."0.9.40" = {
    libc = "0.2.46";
    cc = "1.0.28";
    pkg_config = "0.3.14";
  };
  deps.percent_encoding."1.0.1" = {};
  deps.pkg_config."0.3.14" = {};
  deps.proc_macro2."0.4.24" = {
    unicode_xid = "0.1.0";
  };
  deps.quote."0.6.10" = {
    proc_macro2 = "0.4.24";
  };
  deps.rand."0.3.22" = {
    libc = "0.2.46";
    rand = "0.4.3";
    fuchsia_zircon = "0.3.3";
  };
  deps.rand."0.4.3" = {
    fuchsia_zircon = "0.3.3";
    libc = "0.2.46";
    winapi = "0.3.6";
  };
  deps.redox_syscall."0.1.50" = {};
  deps.regex."0.1.80" = {
    aho_corasick = "0.5.3";
    memchr = "0.1.11";
    regex_syntax = "0.3.9";
    thread_local = "0.2.7";
    utf8_ranges = "0.1.3";
  };
  deps.regex."0.2.11" = {
    aho_corasick = "0.6.9";
    memchr = "2.1.2";
    regex_syntax = "0.5.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.3.9" = {};
  deps.regex_syntax."0.5.6" = {
    ucd_util = "0.1.3";
  };
  deps.remove_dir_all."0.5.1" = {
    winapi = "0.3.6";
  };
  deps.rustc_demangle."0.1.13" = {};
  deps.ryu."0.2.7" = {};
  deps.safemem."0.3.0" = {};
  deps.schannel."0.1.14" = {
    lazy_static = "1.2.0";
    winapi = "0.3.6";
  };
  deps.security_framework."0.1.16" = {
    core_foundation = "0.2.3";
    core_foundation_sys = "0.2.3";
    libc = "0.2.46";
    security_framework_sys = "0.1.16";
  };
  deps.security_framework_sys."0.1.16" = {
    core_foundation_sys = "0.2.3";
    libc = "0.2.46";
  };
  deps.separator."0.4.1" = {};
  deps.serde."1.0.84" = {};
  deps.serde_derive."1.0.84" = {
    proc_macro2 = "0.4.24";
    quote = "0.6.10";
    syn = "0.15.23";
  };
  deps.serde_json."1.0.34" = {
    itoa = "0.4.3";
    ryu = "0.2.7";
    serde = "1.0.84";
  };
  deps.syn."0.15.23" = {
    proc_macro2 = "0.4.24";
    quote = "0.6.10";
    unicode_xid = "0.1.0";
  };
  deps.sys_info."0.5.6" = {
    libc = "0.2.46";
    cc = "1.0.28";
  };
  deps.tempdir."0.3.7" = {
    rand = "0.4.3";
    remove_dir_all = "0.5.1";
  };
  deps.tempfile."2.2.0" = {
    rand = "0.3.22";
    redox_syscall = "0.1.50";
    libc = "0.2.46";
    kernel32_sys = "0.2.2";
    winapi = "0.2.8";
  };
  deps.thread_id."2.0.0" = {
    kernel32_sys = "0.2.2";
    libc = "0.2.46";
  };
  deps.thread_local."0.2.7" = {
    thread_id = "2.0.0";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.2.0";
  };
  deps.time."0.1.41" = {
    libc = "0.2.46";
    redox_syscall = "0.1.50";
    winapi = "0.3.6";
  };
  deps.traitobject."0.1.0" = {};
  deps.typeable."0.1.2" = {};
  deps.ucd_util."0.1.3" = {};
  deps.unicase."1.4.2" = {
    version_check = "0.1.5";
  };
  deps.unicode_bidi."0.3.4" = {
    matches = "0.1.8";
  };
  deps.unicode_normalization."0.1.7" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.url."1.7.2" = {
    idna = "0.1.5";
    matches = "0.1.8";
    percent_encoding = "1.0.1";
  };
  deps.utf8_ranges."0.1.3" = {};
  deps.utf8_ranges."1.0.2" = {};
  deps.uuid."0.4.0" = {
    rand = "0.3.22";
  };
  deps.vcpkg."0.2.6" = {};
  deps.version_check."0.1.5" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.6" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
}
