use ofborg::ghevent::{Repository};

#[derive(Serialize, Deserialize)]
pub struct PullRequestEvent {
    pub action: PullRequestAction,
    pub number: u64,
    pub repository: Repository,
    pub pull_request: PullRequest,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all="snake_case")]
pub enum PullRequestState {
    Open,
    Closed,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all="snake_case")]
pub enum PullRequestAction {
    Assigned,
    Unassigned,
    ReviewRequested,
    ReviewRequestRemoved,
    Labeled,
    Unlabeled,
    Opened,
    Edited,
    Closed,
    Reopened,
    Synchronize,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct PullRequestRef {
    #[serde(rename="ref")]
    pub git_ref: String,
    pub sha: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct PullRequest {
    pub state: PullRequestState,
    pub base: PullRequestRef,
    pub head: PullRequestRef,
}


#[cfg(test)]
mod tests {
    use super::*;
    use serde_json;

    #[test]
    fn test_parse_pr_event() {
        let data =  json!({
            "action": "edited",
            "number": 33299,
            "pull_request": {
                "url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls\\/33299",
                "id": 160662893,
                "html_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs\\/pull\\/33299",
                "diff_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs\\/pull\\/33299.diff",
                "patch_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs\\/pull\\/33299.patch",
                "issue_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues\\/33299",
                "number": 33299,
                "state": "open",
                "locked": false,
                "title": "NixOS Tests: record an flv of the test",
                "user": {
                    "login": "grahamc",
                    "id": 76716,
                    "avatar_url": "https:\\/\\/avatars3.githubusercontent.com\\/u\\/76716?v=4",
                    "gravatar_id": "",
                    "url": "https:\\/\\/api.github.com\\/users\\/grahamc",
                    "html_url": "https:\\/\\/github.com\\/grahamc",
                    "followers_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/followers",
                    "following_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/following{\\/other_user}",
                    "gists_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/gists{\\/gist_id}",
                    "starred_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/starred{\\/owner}{\\/repo}",
                    "subscriptions_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/subscriptions",
                    "organizations_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/orgs",
                    "repos_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/repos",
                    "events_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/events{\\/privacy}",
                    "received_events_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "body": "###### Motivation for this change\r\n\r\nSometimes tests can be hard to debug. Maybe recording an FLV from the VNC could help with that? To start, enable the recording on the flaky keymap test.\r\n\r\n###### Things done\r\n\r\n<!-- Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers. -->\r\n\r\n- [ ] Tested using sandboxing ([nix.useSandbox](http:\\/\\/nixos.org\\/nixos\\/manual\\/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http:\\/\\/nixos.org\\/nix\\/manual\\/#sec-conf-file) on non-NixOS)\r\n- Built on platform(s)\r\n   - [ ] NixOS\r\n   - [ ] macOS\r\n   - [ ] other Linux distributions\r\n- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos\\/tests](https:\\/\\/github.com\\/NixOS\\/nixpkgs\\/blob\\/master\\/nixos\\/tests))\r\n- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run \"nox-review wip\"`\r\n- [ ] Tested execution of all binary files (usually in `.\\/result\\/bin\\/`)\r\n- [ ] Fits [CONTRIBUTING.md](https:\\/\\/github.com\\/NixOS\\/nixpkgs\\/blob\\/master\\/.github\\/CONTRIBUTING.md).\r\n\r\n---\r\n\r\n",
                "created_at": "2018-01-01T22:39:24Z",
                "updated_at": "2018-02-23T21:48:19Z",
                "closed_at": null,
                "merged_at": null,
                "merge_commit_sha": "e145dffca8579ca8fac15497af5f166d1e1197a4",
                "assignee": null,
                "assignees": [],
                "requested_reviewers": [],
                "requested_teams": [],
                "labels": [
                    {
                        "id": 737642262,
                        "url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/labels\\/10.rebuild-darwin:%200",
                        "name": "10.rebuild-darwin: 0",
                        "color": "eeffee",
                        "default": false
                    },
                    {
                        "id": 737642408,
                        "url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/labels\\/10.rebuild-linux:%200",
                        "name": "10.rebuild-linux: 0",
                        "color": "eeffee",
                        "default": false
                    }
                ],
                "milestone": null,
                "commits_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls\\/33299\\/commits",
                "review_comments_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls\\/33299\\/comments",
                "review_comment_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls\\/comments{\\/number}",
                "comments_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues\\/33299\\/comments",
                "statuses_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/statuses\\/887e8b460a7d45ddb3bbdebe01447b251b3229e8",
                "head": {
                    "label": "grahamc:flv-nixos-tests",
                    "ref": "flv-nixos-tests",
                    "sha": "887e8b460a7d45ddb3bbdebe01447b251b3229e8",
                    "user": {
                        "login": "grahamc",
                        "id": 76716,
                        "avatar_url": "https:\\/\\/avatars3.githubusercontent.com\\/u\\/76716?v=4",
                        "gravatar_id": "",
                        "url": "https:\\/\\/api.github.com\\/users\\/grahamc",
                        "html_url": "https:\\/\\/github.com\\/grahamc",
                        "followers_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/followers",
                        "following_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/following{\\/other_user}",
                        "gists_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/gists{\\/gist_id}",
                        "starred_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/starred{\\/owner}{\\/repo}",
                        "subscriptions_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/subscriptions",
                        "organizations_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/orgs",
                        "repos_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/repos",
                        "events_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/events{\\/privacy}",
                        "received_events_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/received_events",
                        "type": "User",
                        "site_admin": false
                    },
                    "repo": {
                        "id": 52226505,
                        "name": "nixpkgs",
                        "full_name": "grahamc\\/nixpkgs",
                        "owner": {
                            "login": "grahamc",
                            "id": 76716,
                            "avatar_url": "https:\\/\\/avatars3.githubusercontent.com\\/u\\/76716?v=4",
                            "gravatar_id": "",
                            "url": "https:\\/\\/api.github.com\\/users\\/grahamc",
                            "html_url": "https:\\/\\/github.com\\/grahamc",
                            "followers_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/followers",
                            "following_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/following{\\/other_user}",
                            "gists_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/gists{\\/gist_id}",
                            "starred_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/starred{\\/owner}{\\/repo}",
                            "subscriptions_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/subscriptions",
                            "organizations_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/orgs",
                            "repos_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/repos",
                            "events_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/events{\\/privacy}",
                            "received_events_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/received_events",
                            "type": "User",
                            "site_admin": false
                        },
                        "private": false,
                        "html_url": "https:\\/\\/github.com\\/grahamc\\/nixpkgs",
                        "description": "Nix Packages collection",
                        "fork": true,
                        "url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs",
                        "forks_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/forks",
                        "keys_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/keys{\\/key_id}",
                        "collaborators_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/collaborators{\\/collaborator}",
                        "teams_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/teams",
                        "hooks_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/hooks",
                        "issue_events_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/issues\\/events{\\/number}",
                        "events_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/events",
                        "assignees_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/assignees{\\/user}",
                        "branches_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/branches{\\/branch}",
                        "tags_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/tags",
                        "blobs_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/git\\/blobs{\\/sha}",
                        "git_tags_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/git\\/tags{\\/sha}",
                        "git_refs_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/git\\/refs{\\/sha}",
                        "trees_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/git\\/trees{\\/sha}",
                        "statuses_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/statuses\\/{sha}",
                        "languages_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/languages",
                        "stargazers_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/stargazers",
                        "contributors_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/contributors",
                        "subscribers_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/subscribers",
                        "subscription_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/subscription",
                        "commits_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/commits{\\/sha}",
                        "git_commits_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/git\\/commits{\\/sha}",
                        "comments_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/comments{\\/number}",
                        "issue_comment_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/issues\\/comments{\\/number}",
                        "contents_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/contents\\/{+path}",
                        "compare_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/compare\\/{base}...{head}",
                        "merges_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/merges",
                        "archive_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/{archive_format}{\\/ref}",
                        "downloads_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/downloads",
                        "issues_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/issues{\\/number}",
                        "pulls_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/pulls{\\/number}",
                        "milestones_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/milestones{\\/number}",
                        "notifications_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/notifications{?since,all,participating}",
                        "labels_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/labels{\\/name}",
                        "releases_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/releases{\\/id}",
                        "deployments_url": "https:\\/\\/api.github.com\\/repos\\/grahamc\\/nixpkgs\\/deployments",
                        "created_at": "2016-02-21T20:31:54Z",
                        "updated_at": "2017-05-07T04:44:29Z",
                        "pushed_at": "2018-01-01T22:35:52Z",
                        "git_url": "git:\\/\\/github.com\\/grahamc\\/nixpkgs.git",
                        "ssh_url": "git@github.com:grahamc\\/nixpkgs.git",
                        "clone_url": "https:\\/\\/github.com\\/grahamc\\/nixpkgs.git",
                        "svn_url": "https:\\/\\/github.com\\/grahamc\\/nixpkgs",
                        "homepage": null,
                        "size": 627435,
                        "stargazers_count": 1,
                        "watchers_count": 1,
                        "language": "Nix",
                        "has_issues": true,
                        "has_projects": true,
                        "has_downloads": true,
                        "has_wiki": false,
                        "has_pages": false,
                        "forks_count": 0,
                        "mirror_url": null,
                        "archived": false,
                        "open_issues_count": 1,
                        "license": {
                            "key": "other",
                            "name": "Other",
                            "spdx_id": null,
                            "url": null
                        },
                        "forks": 0,
                        "open_issues": 1,
                        "watchers": 1,
                        "default_branch": "master"
                    }
                },
                "base": {
                    "label": "NixOS:staging",
                    "ref": "staging",
                    "sha": "19784ca4c9ac378539bdc535b02ae673ba6ba0b0",
                    "user": {
                        "login": "NixOS",
                        "id": 487568,
                        "avatar_url": "https:\\/\\/avatars3.githubusercontent.com\\/u\\/487568?v=4",
                        "gravatar_id": "",
                        "url": "https:\\/\\/api.github.com\\/users\\/NixOS",
                        "html_url": "https:\\/\\/github.com\\/NixOS",
                        "followers_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/followers",
                        "following_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/following{\\/other_user}",
                        "gists_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/gists{\\/gist_id}",
                        "starred_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/starred{\\/owner}{\\/repo}",
                        "subscriptions_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/subscriptions",
                        "organizations_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/orgs",
                        "repos_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/repos",
                        "events_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/events{\\/privacy}",
                        "received_events_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/received_events",
                        "type": "Organization",
                        "site_admin": false
                    },
                    "repo": {
                        "id": 4542716,
                        "name": "nixpkgs",
                        "full_name": "NixOS\\/nixpkgs",
                        "owner": {
                            "login": "NixOS",
                            "id": 487568,
                            "avatar_url": "https:\\/\\/avatars3.githubusercontent.com\\/u\\/487568?v=4",
                            "gravatar_id": "",
                            "url": "https:\\/\\/api.github.com\\/users\\/NixOS",
                            "html_url": "https:\\/\\/github.com\\/NixOS",
                            "followers_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/followers",
                            "following_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/following{\\/other_user}",
                            "gists_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/gists{\\/gist_id}",
                            "starred_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/starred{\\/owner}{\\/repo}",
                            "subscriptions_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/subscriptions",
                            "organizations_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/orgs",
                            "repos_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/repos",
                            "events_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/events{\\/privacy}",
                            "received_events_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/received_events",
                            "type": "Organization",
                            "site_admin": false
                        },
                        "private": false,
                        "html_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs",
                        "description": "Nix Packages collection",
                        "fork": false,
                        "url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs",
                        "forks_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/forks",
                        "keys_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/keys{\\/key_id}",
                        "collaborators_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/collaborators{\\/collaborator}",
                        "teams_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/teams",
                        "hooks_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/hooks",
                        "issue_events_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues\\/events{\\/number}",
                        "events_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/events",
                        "assignees_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/assignees{\\/user}",
                        "branches_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/branches{\\/branch}",
                        "tags_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/tags",
                        "blobs_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/blobs{\\/sha}",
                        "git_tags_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/tags{\\/sha}",
                        "git_refs_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/refs{\\/sha}",
                        "trees_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/trees{\\/sha}",
                        "statuses_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/statuses\\/{sha}",
                        "languages_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/languages",
                        "stargazers_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/stargazers",
                        "contributors_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/contributors",
                        "subscribers_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/subscribers",
                        "subscription_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/subscription",
                        "commits_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/commits{\\/sha}",
                        "git_commits_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/commits{\\/sha}",
                        "comments_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/comments{\\/number}",
                        "issue_comment_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues\\/comments{\\/number}",
                        "contents_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/contents\\/{+path}",
                        "compare_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/compare\\/{base}...{head}",
                        "merges_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/merges",
                        "archive_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/{archive_format}{\\/ref}",
                        "downloads_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/downloads",
                        "issues_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues{\\/number}",
                        "pulls_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls{\\/number}",
                        "milestones_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/milestones{\\/number}",
                        "notifications_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/notifications{?since,all,participating}",
                        "labels_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/labels{\\/name}",
                        "releases_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/releases{\\/id}",
                        "deployments_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/deployments",
                        "created_at": "2012-06-04T02:49:46Z",
                        "updated_at": "2018-02-23T20:56:05Z",
                        "pushed_at": "2018-02-23T21:40:58Z",
                        "git_url": "git:\\/\\/github.com\\/NixOS\\/nixpkgs.git",
                        "ssh_url": "git@github.com:NixOS\\/nixpkgs.git",
                        "clone_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs.git",
                        "svn_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs",
                        "homepage": null,
                        "size": 724069,
                        "stargazers_count": 2239,
                        "watchers_count": 2239,
                        "language": "Nix",
                        "has_issues": true,
                        "has_projects": true,
                        "has_downloads": true,
                        "has_wiki": false,
                        "has_pages": false,
                        "forks_count": 2580,
                        "mirror_url": null,
                        "archived": false,
                        "open_issues_count": 2860,
                        "license": {
                            "key": "other",
                            "name": "Other",
                            "spdx_id": null,
                            "url": null
                        },
                        "forks": 2580,
                        "open_issues": 2860,
                        "watchers": 2239,
                        "default_branch": "master"
                    }
                },
                "_links": {
                    "self": {
                        "href": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls\\/33299"
                    },
                    "html": {
                        "href": "https:\\/\\/github.com\\/NixOS\\/nixpkgs\\/pull\\/33299"
                    },
                    "issue": {
                        "href": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues\\/33299"
                    },
                    "comments": {
                        "href": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues\\/33299\\/comments"
                    },
                    "review_comments": {
                        "href": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls\\/33299\\/comments"
                    },
                    "review_comment": {
                        "href": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls\\/comments{\\/number}"
                    },
                    "commits": {
                        "href": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls\\/33299\\/commits"
                    },
                    "statuses": {
                        "href": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/statuses\\/887e8b460a7d45ddb3bbdebe01447b251b3229e8"
                    }
                },
                "author_association": "MEMBER",
                "merged": false,
                "mergeable": null,
                "rebaseable": null,
                "mergeable_state": "unknown",
                "merged_by": null,
                "comments": 5,
                "review_comments": 0,
                "maintainer_can_modify": true,
                "commits": 1,
                "additions": 41,
                "deletions": 4,
                "changed_files": 4
            },
            "changes": {
                "base": {
                    "ref": {
                        "from": "master"
                    },
                    "sha": {
                        "from": "a6664d8192038c4dc2ad44169dbb76556fe71ac1"
                    }
                }
            },
            "repository": {
                "id": 4542716,
                "name": "nixpkgs",
                "full_name": "NixOS\\/nixpkgs",
                "owner": {
                    "login": "NixOS",
                    "id": 487568,
                    "avatar_url": "https:\\/\\/avatars3.githubusercontent.com\\/u\\/487568?v=4",
                    "gravatar_id": "",
                    "url": "https:\\/\\/api.github.com\\/users\\/NixOS",
                    "html_url": "https:\\/\\/github.com\\/NixOS",
                    "followers_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/followers",
                    "following_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/following{\\/other_user}",
                    "gists_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/gists{\\/gist_id}",
                    "starred_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/starred{\\/owner}{\\/repo}",
                    "subscriptions_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/subscriptions",
                    "organizations_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/orgs",
                    "repos_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/repos",
                    "events_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/events{\\/privacy}",
                    "received_events_url": "https:\\/\\/api.github.com\\/users\\/NixOS\\/received_events",
                    "type": "Organization",
                    "site_admin": false
                },
                "private": false,
                "html_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs",
                "description": "Nix Packages collection",
                "fork": false,
                "url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs",
                "forks_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/forks",
                "keys_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/keys{\\/key_id}",
                "collaborators_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/collaborators{\\/collaborator}",
                "teams_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/teams",
                "hooks_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/hooks",
                "issue_events_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues\\/events{\\/number}",
                "events_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/events",
                "assignees_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/assignees{\\/user}",
                "branches_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/branches{\\/branch}",
                "tags_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/tags",
                "blobs_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/blobs{\\/sha}",
                "git_tags_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/tags{\\/sha}",
                "git_refs_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/refs{\\/sha}",
                "trees_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/trees{\\/sha}",
                "statuses_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/statuses\\/{sha}",
                "languages_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/languages",
                "stargazers_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/stargazers",
                "contributors_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/contributors",
                "subscribers_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/subscribers",
                "subscription_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/subscription",
                "commits_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/commits{\\/sha}",
                "git_commits_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/git\\/commits{\\/sha}",
                "comments_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/comments{\\/number}",
                "issue_comment_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues\\/comments{\\/number}",
                "contents_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/contents\\/{+path}",
                "compare_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/compare\\/{base}...{head}",
                "merges_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/merges",
                "archive_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/{archive_format}{\\/ref}",
                "downloads_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/downloads",
                "issues_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/issues{\\/number}",
                "pulls_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/pulls{\\/number}",
                "milestones_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/milestones{\\/number}",
                "notifications_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/notifications{?since,all,participating}",
                "labels_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/labels{\\/name}",
                "releases_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/releases{\\/id}",
                "deployments_url": "https:\\/\\/api.github.com\\/repos\\/NixOS\\/nixpkgs\\/deployments",
                "created_at": "2012-06-04T02:49:46Z",
                "updated_at": "2018-02-23T20:56:05Z",
                "pushed_at": "2018-02-23T21:40:58Z",
                "git_url": "git:\\/\\/github.com\\/NixOS\\/nixpkgs.git",
                "ssh_url": "git@github.com:NixOS\\/nixpkgs.git",
                "clone_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs.git",
                "svn_url": "https:\\/\\/github.com\\/NixOS\\/nixpkgs",
                "homepage": null,
                "size": 724069,
                "stargazers_count": 2239,
                "watchers_count": 2239,
                "language": "Nix",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": false,
                "forks_count": 2580,
                "mirror_url": null,
                "archived": false,
                "open_issues_count": 2860,
                "license": {
                    "key": "other",
                    "name": "Other",
                    "spdx_id": null,
                    "url": null
                },
                "forks": 2580,
                "open_issues": 2860,
                "watchers": 2239,
                "default_branch": "master"
            },
            "organization": {
                "login": "NixOS",
                "id": 487568,
                "url": "https:\\/\\/api.github.com\\/orgs\\/NixOS",
                "repos_url": "https:\\/\\/api.github.com\\/orgs\\/NixOS\\/repos",
                "events_url": "https:\\/\\/api.github.com\\/orgs\\/NixOS\\/events",
                "hooks_url": "https:\\/\\/api.github.com\\/orgs\\/NixOS\\/hooks",
                "issues_url": "https:\\/\\/api.github.com\\/orgs\\/NixOS\\/issues",
                "members_url": "https:\\/\\/api.github.com\\/orgs\\/NixOS\\/members{\\/member}",
                "public_members_url": "https:\\/\\/api.github.com\\/orgs\\/NixOS\\/public_members{\\/member}",
                "avatar_url": "https:\\/\\/avatars3.githubusercontent.com\\/u\\/487568?v=4",
                "description": ""
            },
            "sender": {
                "login": "grahamc",
                "id": 76716,
                "avatar_url": "https:\\/\\/avatars3.githubusercontent.com\\/u\\/76716?v=4",
                "gravatar_id": "",
                "url": "https:\\/\\/api.github.com\\/users\\/grahamc",
                "html_url": "https:\\/\\/github.com\\/grahamc",
                "followers_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/followers",
                "following_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/following{\\/other_user}",
                "gists_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/gists{\\/gist_id}",
                "starred_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/starred{\\/owner}{\\/repo}",
                "subscriptions_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/subscriptions",
                "organizations_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/orgs",
                "repos_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/repos",
                "events_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/events{\\/privacy}",
                "received_events_url": "https:\\/\\/api.github.com\\/users\\/grahamc\\/received_events",
                "type": "User",
                "site_admin": false
            }
        });

        let _p: PullRequestEvent =
            serde_json::from_str(&data.to_string())
            .expect("Should properly deserialize");
    }
}
