name: CI

on:
  push:
    branches: [released]
  pull_request:

jobs:
  checkPhase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Set up git
        run: |
          git config --global user.email "ofborg@example.com"
          git config --global user.name "ofborg"
      - name: checkPhase
        run: nix-shell --pure --run checkPhase

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: nix-build
        run: nix-build -A ofborg.rs -A ofborg.php
